# Generated by Django 5.2.5 on 2025-08-16 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_productcategory_productitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='category',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='ProductItem',
        ),
    ]
